--------------------------------------------------------
--  Arquivo criado - sexta-feira-outubro-11-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CROP
--------------------------------------------------------

  CREATE TABLE "RM559712"."CROP" 
   (	"CRP_ID" NUMBER(*,0), 
	"CRP_NAME" VARCHAR2(50 BYTE), 
	"CRP_TEMP_MIN" NUMBER(10,4), 
	"CRP_TEMP_MAX" NUMBER(10,4), 
	"CRP_HUMIDITY_MIN" NUMBER(10,4), 
	"CRP_HUMIDITY_MAX" NUMBER(10,4), 
	"CRP_WIND_SPEED_MIN" NUMBER(10,4), 
	"CRP_WIND_SPEED_MAX" NUMBER(10,4), 
	"CRP_RAIN_MIN" NUMBER(10,4), 
	"CRP_RAIN_MAX" NUMBER(10,4), 
	"CRP_STATUS" NUMBER(*,0) DEFAULT 1, 
	"CRP_INSERT_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"CRP_UPDATE_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;

   COMMENT ON COLUMN "RM559712"."CROP"."CRP_STATUS" IS '0: Inativo, 1: Ativo';
REM INSERTING into RM559712.CROP
SET DEFINE OFF;
Insert into RM559712.CROP (CRP_ID,CRP_NAME,CRP_TEMP_MIN,CRP_TEMP_MAX,CRP_HUMIDITY_MIN,CRP_HUMIDITY_MAX,CRP_WIND_SPEED_MIN,CRP_WIND_SPEED_MAX,CRP_RAIN_MIN,CRP_RAIN_MAX,CRP_STATUS,CRP_INSERT_DATE,CRP_UPDATE_DATE) values ('2','Café',null,'35,5','25,5','40,1','10','30,8','12,1','30','1',to_timestamp('09/10/24 14:09:34,562610000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('09/10/24 21:25:55,418275000','DD/MM/RR HH24:MI:SSXFF'));
Insert into RM559712.CROP (CRP_ID,CRP_NAME,CRP_TEMP_MIN,CRP_TEMP_MAX,CRP_HUMIDITY_MIN,CRP_HUMIDITY_MAX,CRP_WIND_SPEED_MIN,CRP_WIND_SPEED_MAX,CRP_RAIN_MIN,CRP_RAIN_MAX,CRP_STATUS,CRP_INSERT_DATE,CRP_UPDATE_DATE) values ('1','Cana-de-açúcar','16,9','26,2','19','27,2','4','12,8','12','29,8','1',to_timestamp('09/10/24 14:07:58,994340000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('11/10/24 14:01:29,433027000','DD/MM/RR HH24:MI:SSXFF'));
--------------------------------------------------------
--  DDL for Index CROPS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM559712"."CROPS_PK" ON "RM559712"."CROP" ("CRP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_CRP_UPDATE_DATE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "RM559712"."TRIGGER_CRP_UPDATE_DATE" 
BEFORE UPDATE ON "CROP"
FOR EACH ROW
BEGIN
    :NEW.CRP_UPDATE_DATE := CURRENT_TIMESTAMP;  -- Atualiza a coluna com a data/hora atual
END;
/
ALTER TRIGGER "RM559712"."TRIGGER_CRP_UPDATE_DATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_CRP_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "RM559712"."TRIGGER_CRP_ID" 
BEFORE INSERT ON CROP 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CRP_ID IS NULL THEN
      SELECT CROP_SEQ.NEXTVAL INTO :NEW.CRP_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "RM559712"."TRIGGER_CRP_ID" ENABLE;
--------------------------------------------------------
--  Constraints for Table CROP
--------------------------------------------------------

  ALTER TABLE "RM559712"."CROP" ADD CONSTRAINT "CROPS_PK" PRIMARY KEY ("CRP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM559712"."CROP" MODIFY ("CRP_ID" NOT NULL ENABLE);
  ALTER TABLE "RM559712"."CROP" MODIFY ("CRP_NAME" NOT NULL ENABLE);
  ALTER TABLE "RM559712"."CROP" MODIFY ("CRP_STATUS" NOT NULL ENABLE);
  ALTER TABLE "RM559712"."CROP" MODIFY ("CRP_INSERT_DATE" NOT NULL ENABLE);
